CREATE DATABASE vegmap;

USE vegmap;

CREATE TABLE usuario(
idusuario TINYINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nome VARCHAR(30) NOT NULL,
telefone TINYINT NOT NULL,
email VARCHAR(50) NOT NULL,
senha VARCHAR(25) NOT NULL
);

CREATE TABLE usuariopc(
idusuarioPC TINYINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nomePC VARCHAR(30) NOT NULL,
cnpj INT NOT NULL,
telefonePC TINYINT NOT NULL,
emailPC VARCHAR(50) NOT NULL,
senhaPC VARCHAR(25) NOT NULL
);

CREATE TABLE estabelecimento(
idestab TINYINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nome_estab VARCHAR(30) NOT NULL,
endereco VARCHAR(40) NOT NULL,
telefone_estab TINYINT NOT NULL,
descricaoestab VARCHAR(320) NOT NULL,
idusuarioPC TINYINT NOT NULL,
tipo VARCHAR(20) NOT NULL,

FOREIGN KEY (idusuarioPC) REFERENCES usuariopc(idusuarioPC)
);

CREATE TABLE produto(
idProdu TINYINT PRIMARY KEY AUTO_INCREMENT,
nomeProdu VARCHAR(20) NOT NULL,
tipoProdu VARCHAR(20) NOT NULL,
medidaProdu VARCHAR(10) NOT NULL,
saborProdu VARCHAR(15) NULL
);

CREATE TABLE avaliacao(
idAvaliacao TINYINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nota INT NOT NULL,
comentario VARCHAR(300) NULL,
idestab TINYINT NOT NULL,

FOREIGN KEY (idestab) REFERENCES estabelecimento (idestab) 
);

CREATE TABLE avaliacaop(
idAvaliacaoP TINYINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
notaP INT NOT NULL,
comentarioP VARCHAR(300) NULL,
idProdu TINYINT NOT NULL,

FOREIGN KEY (idProdu) REFERENCES produto (idProdu)
);